### ISSUE TITLE
2D image to generate persistence 

### ISSUE THREAD

**Issue by hellorp1990** [MathieuCarriere/sklearn_tda#1]
Hi,
I have a problem generating betti curve or persistence image from a 2D array (a gray scale image).
But I am getting this error,
ValueError: too many values to unpack (expected 2) 

I understand what the error is, but can I apply to a larger array other than the size of 2.

**Comment by MathieuCarriere** [comment]
Hi,
BettiCurve and PersistenceImage expect the input to be a list of persistence diagrams, and each persistence diagram is represented as a 2D numpy array. I do not think that the code can handle another input type for now, especially if you are using cython.

Can you tell me what is exactly the type of your input (type, dimension...)? Also, remember that this code takes persistence diagrams as input and does not perform the diagram computation itself from raw data. It is rather devoted to the post processing of the persistence diagrams themselves.

Best,
Mathieu

**Comment by hellorp1990** [comment]
Hi Mathieu,
I have tried both PersistenceImage and betti curve but i found errors.
I have used 2D numpy array. I checked the type of the array.
The size of the image is 30x30. It's a grayscale image (2 dimensional). 
I tried to use the example shown in https://github.com/MathieuCarriere/sklearn_tda/blob/master/example/example_of_computations.py


but the error is:
File "ex.py", line 57, in <module>
    B = BC.fit_transform(diags)
  File "/usr/local/lib/python3.6/site-packages/sklearn/base.py", line 517, in fit_transform
    return self.fit(X, **fit_params).transform(X)
  File "/usr/local/lib/python3.6/site-packages/sklearn_tda/code.py", line 301, in fit
    [mx,my],[Mx,My] = pre.scaler.data_min_, pre.scaler.data_max_
ValueError: too many values to unpack (expected 2)

Any help?
my code is shown below,

import sklearn_tda as tda
import matplotlib.pyplot as plt
import numpy as np
import matplotlib.image as mpimg
import cv2
import math

def arctan(C,p):
  return lambda x: C*np.arctan(np.power(x[1], p))

img=cv2.imread('78.png')
print(img.shape)
print (type(img))
diags=[gray]

BC = tda.BettiCurve(resolution = 1000)
B = BC.fit_transform(diags)
print(B.shape)
plt.plot(B[0])
plt.show()


Rahul

**Comment by MathieuCarriere** [comment]
I guess gray is the name of your 30 x 30 input image.
I think there is an error because the code expects a list of persistence diagrams, i.e. n x 2 numpy arrays. Since your second dimension is 30 instead of 2, this raises an error.
Persistence images and Betti curves are methods that vectorize persistence diagrams but they do not compute the diagrams themselves.

Mathieu

**Comment by hellorp1990** [comment]
Hi Mathieu,
Thanks for the help. I understood it now.

Rahul
