### ISSUE TITLE
Minor error in clustering.py

### ISSUE THREAD

**Issue by ewancarr** [MathieuCarriere/sklearn_tda#6]
https://github.com/MathieuCarriere/sklearn_tda/blob/3e281995f589660b7edf92c254307bb19c5f3482/sklearn_tda/clustering.py#L223

In the above line, I think `clus_colors` should be `clus_colors_`. (I couldn't get it to work without making this change).

**Comment by MathieuCarriere** [comment]
Hi Ewan,
Thanks for the comment. You are totally right, so I fixed this line.
Mathieu
