### ISSUE TITLE
Error when `col_vals` is empty

### ISSUE THREAD

**Issue by ewancarr** [MathieuCarriere/sklearn_tda#7]
I'm having a problem where, for some bootstrap iterations, the `col_vals` variable is empty, and consequently, `min(col_vals)` and `max(col_vals)` fail.

https://github.com/MathieuCarriere/sklearn_tda/blob/a0602ab42550f292e557ba70646f5d0191a56cf0/sklearn_tda/clustering.py#L222-L231

I think this is happens when, for a given bootstrap iteration, the `MapperComplex` object contains no nodes (and therefore, no colors). But I may be wrong.

I'm fixing this for now by simply adding the following conditional statement to `compute_persistence_diagrams`:

```python
if col_vals == {}:
    col_vals = {0: 0}         
```
However, this might be a terrible idea and other solutions would be welcome.

**Comment by MathieuCarriere** [comment]
Hi Ewan,

Thanks for your message. 

What surprises me is that `MapperComplex` objects computed from bootstrap iterations should always have at least one node (provided that the original `MapperComplex` also has at least one). Having no nodes means (I think) that either there is no input data, or the filter boundaries are specified manually (with the `filter_bnds` variables) and do not encompass the data filter values.

Is this what is happening for you?

**Comment by MathieuCarriere** [comment]
Closing for now, do not hesitate to re-open if problem persists!
