### ISSUE TITLE
error when changing the ex_diagrams.py

### ISSUE THREAD

**Issue by Chen-Cai-OSU** [MathieuCarriere/sklearn_tda#9]
Hi Mathieu,

In the ex_diagrams.py, if I change line 11 from diags = [D] to diags = [D, D]. I will encounter the following error. I used the older version of sklearn-tda before and encounted this new bug after the update. I believe this might be due to the recent updates of sklearn_tda.

```
Traceback (most recent call last):
  File "ex_diagrams.py", line 14, in <module>
    L = LS.fit_transform(diags)
  File "/home/cai.507/anaconda3/lib/python3.6/site-packages/sklearn/base.py", line 464, in fit_transform
    return self.fit(X, **fit_params).transform(X)
  File "/home/cai.507/anaconda3/lib/python3.6/site-packages/sklearn_tda/vector_methods.py", line 152, in transform
    Xfit.append(np.sqrt(2)*np.reshape(ls,[1,-1]))
AttributeError: 'numpy.ndarray' object has no attribute 'append'

```

**Comment by MathieuCarriere** [comment]
Hi Chen,

Thanks for your message. Indeed, there were an issue with tabs in the code. I just fixed it so running ex_diagrams.py with diags=[D,D] should work now.

Mathieu

**Comment by Chen-Cai-OSU** [comment]
Awesome. Thanks!
